name: uskyrim
description: A Skyrim progress tracking app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.14
  mockito: ^5.4.5
  hive_test: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/json/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
